name: build_windows

on:
  push:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout luna repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the version you need

      - name: Generate solution files and install Vulkan
        run: .\build.bat


      - name: Archive repository
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: repo-archive
          path: ${{ github.workspace }}

  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build-configuration: [debug, release, distribution]
        configuration: [luna.sln, lunaScripting.sln]

    env:
      CORE_SOLUTION_FILE_PATH: luna.sln
      SCRIPTING_SOLUTION_FILE_PATH: lunaScripting.sln

    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Cache specific directories
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/bin-int
            ${{ github.workspace }}/bin
          key: ${{ runner.os }}-bin-dirs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bin-dirs-
      - name: Download repository archive
        uses: actions/download-artifact@v2
        with:
          name: repo-archive

      - name: Build ${{matrix.configuration}} Engine
        run: msbuild /m /p:Configuration=${{ matrix.build-configuration }} ${{ matrix.configuration }}
      
