name: build_windows

on:
  push:
  
jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Cache entire repository
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}
          key: ${{ runner.os }}-repo-cache
      - name: Checkout luna repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.216.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Cross
          vulkan-use-cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the version you need

      - name: Generate solution files and install Vulkan
        run: .\build.bat

  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build-configuration: [debug, release, distribution]
        configuration: [luna.sln, lunaScripting.sln]

    env:
      CORE_SOLUTION_FILE_PATH: luna.sln
      SCRIPTING_SOLUTION_FILE_PATH: lunaScripting.sln

    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.216.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Cross
          vulkan-use-cache: true
      - name: Cache entire repository
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}
          key: ${{ runner.os }}-repo-cache
          restore-keys: |
            ${{ runner.os }}-repo-cache
      - name: Cache specific build directories
        if: matrix.configuration != 'lunaScripting.sln'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/bin-int
            ${{ github.workspace }}/bin
          key: ${{ runner.os }}-specific-build-dirs-${{ matrix.configuration }}
          restore-keys: |
            ${{ runner.os }}-specific-build-dirs-${{ matrix.configuration }}
  
      - name: Build ${{matrix.configuration}} Engine
        run: msbuild /m /p:Configuration=${{ matrix.build-configuration }} ${{ matrix.configuration }}
