name: build_windows

on:
  push:

env:
  CORE_SOLUTION_FILE_PATH: luna.sln
  SCRIPTING_SOLUTION_FILE_PATH: lunaScripting.sln

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout luna repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.216.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Cross
          vulkan-use-cache: true

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the version you need

      - name: Generate solution files and install Vulkan
        run: .\build.bat

      - name: Archive entire repository
        uses: actions/upload-artifact@v2
        with:
          name: entire-repo
          path: |
            .  # Include the entire repository
          
  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build-configuration: [debug, release, distribution]
    steps:
      - name: Download entire repository
        uses: actions/download-artifact@v2
        with:
          name: entire-repo
          path: ${{ github.workspace }}

      - name: Build Core Engine
        working-directory: ${{ github.workspace }}
        run: msbuild /m /p:Configuration=${{ matrix.build-configuration }} ${{ env.CORE_SOLUTION_FILE_PATH }}

      - name: Build Scripting Engine
        working-directory: ${{ github.workspace }}
        run: msbu
