name: build_windows

on:
  push:


env:
  CORE_SOLUTION_FILE_PATH: luna.sln
  SCRIPTING_SOLUTION_FILE_PATH: lunaScripting.sln

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout luna repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.216.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Cross
          vulkan-use-cache: true

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the version you need

      - name: Generate solution files and install Vulkan
        run: .\build.bat

      - name: Cache entire repository
        uses: actions/cache@v3
        with:
          path: |
            .  # Include the entire repository
          key: ${{ runner.os }}-entire-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-entire-repo-

  build:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        build-configuration: [debug, release, distribution]
    steps:
      - name: Restore entire repository from cache
        uses: actions/cache@v3
        with:
          path: |
            .  # Include the entire repository
          key: ${{ runner.os }}-entire-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-entire-repo-

      - name: List files in the restored repository
        run: |
          ls -R .

      - name: Build Core Engine
        run: msbuild /m /p:Configuration=${{ matrix.build-configuration }} ${{ env.CORE_SOLUTION_FILE_PATH }}

      - name: Build Scripting Engine
        run: msbuild /m /p:Configuration=${{ matrix.build-configuration }} ${{ env.SCRIPTING_SOLUTION_FILE_PATH }}
